---
- hosts: testswitch
  gather_facts: no

  tasks:
    
  - name: BACKUP VERSION
    ios_command:
      commands:
        - show version
    register: version
    vars:
      ansible_command_timeout: 180 

  - name: SAVE CONFIG TO LOCAL REPO
    copy:
      content: "{{ version.stdout[0]}}"
      dest: "/home/gitlab_repo/backup/{{ inventory_hostname }}.txt"

  - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
    shell: bash /home/gitlab_repo/bash/git-push 
 
