---
- hosts: testswitch
  gather_facts: no

  tasks:

  - name: GATHER FACTS
    ios_facts:
    
  - name: RUN SHOW INTERFACES 
    ios_command:
      commands:
         - show ip interface brief
    register: ipbrief

  - debug: var=ipbrief.stdout_lines 
