#!/bin/bash

echo "Syncing to Git"
echo `whoami`  CHECK
#Get current date for commit
currentdate=$(date +%d-%b-%Y)
gitcommittime=$(date +%d-%b-%Y-%H:%M)

# Location of the git folder collection
#mygitfolder=/ansible/cloned_local_repositories/
mygitfolder=/ansible/cloned_local_repositories/genie-structured

# Loop through all folders and place the names in an array
#git_folders=()
#while IFS= read -r line; do
#    git_folders+=( "$line" )
#  done< <(ls /ansible/cloned_local_repositories/genie-structured)

# Loop through the array and run the commands needed to automaticly push a repo to github,
# git add, commit, push(IF commit executed sucsessfully meaning it was something to commit in that folder)
##for config in `ls ${mygitfolder}`
#do
   cd "$mygitfolder"
# sudo -u ansible /usr/bin/git add .
# sudo -u ansible /usr/bin/git commit -a -m ${gitcommittime}
# sudo -u ansible /usr/bin/git push
 /usr/bin/git add .
 /usr/bin/git commit -a -m ${gitcommittime}
 /usr/bin/git push

#done


